on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  ctx:
    runs-on: ubuntu-latest
    steps:
      - name: Event Type
        env:
          GITHUB_CTX: ${{ toJson(github) }}
        run: echo "$GITHUB_CTX"
